apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - ingress-nginx
  - sealed-secrets
  - cloudflared
  - external-dns
  - kyverno
  - kyverno-policies
  - metrics-server
  - argocd
